# Generated by Django 4.2.2 on 2023-07-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_search_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='web.quote'),
        ),
    ]
