# Generated by Django 4.2.2 on 2023-07-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_search_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='publish_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
