# Generated by Django 4.2.2 on 2023-07-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_search_publish_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
    ]
